import {logout} from "./auth.js";
import {saveOnboarding,generatePlan} from "./onboarding.js";
const API=window.IRONCOACH_API||localStorage.getItem("ironcoach_api")||"https://ironcoach-api.onrender.com";
let tab=localStorage.getItem("ironcoach_tab")||"Hoy";
let today={state:null,workout:null,loading:false},plan=null,progress=null;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function get(p){const r=await fetch(API+p,{credentials:"include"});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||r.status);return d}
async function post(p,b={}){const r=await fetch(API+p,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||r.status);return d}
function onboardingScreen(){return `<div class="shell"><main><div class="kicker">IRONCOACH · ONBOARDING</div><div class="title">Vamos a construir tu plan</div><div class="card"><div class="h3">Tu perfil de atleta</div><div class="label">NIVEL GENERAL</div><select id="level" class="authinput"><option value="beginner">Principiante</option><option value="intermediate">Intermedio</option><option value="advanced">Avanzado</option></select><div class="label">PESO · KG</div><input id="weight" class="authinput" type="number" step="0.1" placeholder="86"><div class="label">HORAS / SEMANA</div><input id="hours" class="authinput" type="number" step="0.5" value="8"><div class="label">TU LIMITER PRINCIPAL</div><select id="limiter" class="authinput"><option value="bike">Bike</option><option value="run">Run</option><option value="swim">Swim</option></select><button class="action" onclick="finishOnboarding()">Generar mi plan →</button></div><div class="muted">Tu cuenta es personal y se identifica mediante tu conexión con Strava.</div></main></div>`}
window.finishOnboarding=async()=>{try{const level=document.getElementById("level").value;await saveOnboarding({weight_kg:Number(document.getElementById("weight").value)||null,weekly_hours_target:Number(document.getElementById("hours").value)||8,swim_level:level,bike_level:level,run_level:level,race_name:"IRONMAN 70.3 Valencia 2027",race_date:"2027-04-18"});await generatePlan(document.getElementById("limiter").value);localStorage.removeItem("ironcoach_onboarding");localStorage.setItem("ironcoach_tab","Hoy");location.reload()}catch(e){alert(e.message)}};
async function hasSession(){try{return (await fetch(API+"/profile",{credentials:"include"})).ok}catch{return false}}
async function renderGate(){if(!(await hasSession())){try{await get("/auth/bootstrap")}catch(e){document.getElementById("app").innerHTML=`<div class="shell"><main><div class="kicker">IRONCOACH</div><div class="title">No puedo iniciar IronCoach</div><div class="card">${esc(e.message)}</div></main></div>`;return}if(!(await hasSession()))return}if(localStorage.getItem("ironcoach_onboarding")==="1"){document.getElementById("app").innerHTML=onboardingScreen();return}try{const p=await get("/profile");if(!p.athlete.weight_kg)localStorage.setItem("ironcoach_onboarding","1")}catch{}if(localStorage.getItem("ironcoach_onboarding")==="1"){document.getElementById("app").innerHTML=onboardingScreen();return}render();if(tab==="Hoy")loadToday()}
function metric(n,v){return `<div class="metric"><span>${n}</span><b>${v==null?"—":Math.round(v)}</b></div>`}
async function loadToday(){today.loading=true;render();try{const[a,w]=await Promise.all([get("/today/state"),get("/today/workout")]);today={state:a,workout:w.workout,loading:false}}catch(e){today.loading=false}render()}
async function loadPlan(){try{plan=await get("/plan/current")}catch{plan=null}render()}
async function loadProgress(){try{progress=await get("/progress")}catch{progress=null}render()}
function todayView(){if(today.loading)return `<div class="loading">Cargando tu estado…</div>`;const s=today.state||{},w=today.workout;return `<div class="kicker">HOY · ${esc(s.date||"")}</div><div class="title">Tu día de entrenamiento</div><div class="card"><div class="label">READINESS</div><div class="score">${s.readiness==null?"—":Math.round(s.readiness)}</div><div class="muted">${esc(s.reason||"Estado calculado con tus datos disponibles")}</div></div><div class="card"><div class="label">SESIÓN</div><div class="h3">${w?esc(w.title):"No hay sesión programada"}</div><div class="muted">${w?`${esc(w.sport)} · ${w.duration_min} min · ${esc(w.intensity)} · ${esc(w.objective)}`:"Genera un plan para empezar."}</div>${w?`<button class="action" onclick="feedback(${w.id})">Registrar sesión</button>`:""}</div><div class="card"><div class="label">TU ESTADO</div>${metric("Recovery",s.recovery)}${metric("Fatigue",s.fatigue)}${metric("Fitness",s.fitness)}${metric("Consistency",s.consistency)}${metric("Load / Recovery Risk",s.injury_risk)}</div>`}
function planView(){if(!plan?.plan)return `<div class="kicker">PLAN</div><div class="title">Tu preparación</div><div class="card empty">Todavía no hay un plan generado.</div>`;return `<div class="kicker">PLAN · v${plan.plan.version}</div><div class="title">Valencia 70.3</div>`+(plan.plan.weeks||[]).slice(0,6).map((w,i)=>`<div class="card"><div class="label">SEMANA ${i+1} · ${esc(w.phase)}</div><div class="h3">${esc(w.objective_primary||"Objetivo semanal")}</div><div class="muted">Desde ${esc(w.week_start)} · presupuesto ${Math.round(w.load_budget||0)} load</div>${(w.workouts||[]).map(x=>`<div class="metric"><span>${esc(x.date)} · ${esc(x.sport)} · ${esc(x.title)}</span><b>${x.duration_min}'</b></div>`).join("")}</div>`).join("")}
function progressView(){if(!progress?.series?.length)return `<div class="kicker">PROGRESO</div><div class="title">Evolución</div><div class="card empty">Aún no hay histórico. Tus datos aparecerán aquí al entrenar.</div>`;const a=progress.series.at(-1);return `<div class="kicker">PROGRESO</div><div class="title">Cómo estás evolucionando</div>`+[["FITNESS",a.fitness],["RECOVERY",a.recovery],["READINESS",a.readiness],["CONSISTENCY",a.consistency],["LOAD / RECOVERY RISK",a.risk],["FINISH CONFIDENCE",a.finish_confidence]].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="score">${x[1]==null?"—":Math.round(x[1])}</div><div class="muted">Último estado: ${esc(a.date)}</div></div>`).join("")}
function coachView(){return `<div class="kicker">COACH</div><div class="title">Tu entrenador</div><div class="chat"><div id="messages" class="messages"><div class="bubble ai">Pregúntame por tu sesión, recuperación, carga o por qué he adaptado el plan.</div></div><div class="composer"><input id="msg" placeholder="¿Por qué tengo esta sesión?"><button onclick="send()">→</button></div></div>`}
function profileView(){return `<div class="kicker">PERFIL</div><div class="title">IronCoach</div><div class="card"><div class="h3">IRONMAN 70.3 Valencia 2027</div><div class="muted">18 abril 2027 · objetivo: llegar con buenas sensaciones.</div></div><div class="card"><div class="metric"><span>Garmin</span><b>Próximamente</b></div><div class="metric"><span>Strava</span><button class="mini" onclick="connectStrava()">Conectar →</button></div><div id="stravaStatus" class="muted">Comprobando conexión…</div><button class="action secondary" onclick="importStrava()">Sincronizar Strava ahora</button><div class="metric"><span>Apple Health</span><b>iPhone · próximamente</b></div></div><div class="card"><button class="action secondary" onclick="logout()">Cerrar sesión</button></div>`}
function render(){document.getElementById("app").innerHTML=`<div class="shell"><header><div class="brand">IRONCOACH</div><div class="race">70.3 VALENCIA · 2027</div></header><main>${tab==="Hoy"?todayView():tab==="Plan"?planView():tab==="Progreso"?progressView():tab==="Coach"?coachView():profileView()}</main><nav class="nav">${["Hoy","Plan","Progreso","Coach","Perfil"].map(x=>`<button class="${tab===x?"active":""}" onclick="go('${x}')">${x}</button>`).join("")}</nav></div>`}
window.go=async x=>{tab=x;localStorage.setItem("ironcoach_tab",x);render();if(x==="Hoy")loadToday();if(x==="Plan")loadPlan();if(x==="Progreso")loadProgress();if(x==="Perfil")loadStravaStatus()};
window.feedback=async id=>{const r=prompt("¿Qué RPE tuvo la sesión? (1-10)","5");if(r===null)return;const notes=prompt("Notas opcionales","")||"";try{await post(`/plan/workouts/${id}/feedback`,{actual_duration_min:today.workout.duration_min,actual_rpe:Number(r),notes});alert("Feedback guardado. IronCoach evaluará la siguiente sesión.");loadToday()}catch(e){alert(e.message)}};
window.send=async()=>{const i=document.getElementById("msg"),q=i.value.trim();if(!q)return;i.value="";const b=document.getElementById("messages");b.innerHTML+=`<div class="bubble me">${esc(q)}</div>`;try{const d=await post("/coach/chat",{message:q,mode:"coach"});b.innerHTML+=`<div class="bubble ai">${esc(d.text||"No he podido responder.")}</div>`}catch{b.innerHTML+=`<div class="bubble ai">No puedo conectar con el Coach ahora.</div>`}};
window.connectStrava=async()=>{try{const d=await get("/integrations/strava/connect");location.href=d.authorization_url}catch(e){alert(e.message)}};
window.importStrava=async()=>{try{const d=await post("/integrations/strava/import",{});alert(`Strava: ${d.imported} actividades importadas`);loadToday()}catch(e){alert(e.message)}};
async function loadStravaStatus(){try{const d=await get("/integrations/strava/status");const el=document.getElementById("stravaStatus");if(el)el.textContent=d.connected?"Conectado · Strava listo para sincronizar":"No conectado"}catch{}}
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js?v=4").then(r=>r.update()).catch(()=>{});
renderGate();
